# Generated by Django 4.0.2 on 2022-02-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post_delete_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='description',
        ),
    ]
